name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      qa_image_name:
        description: "The tag of the docker image in QA that we want to move to PROD"
        type: string
        required: true
      prod_image_name:
        description: "The tag we want to give the docker image that is being put into PROD"
        type: string
        required: true

permissions:
  id-token: write   # This is required by AWS for requesting the JWT
  contents: read    # This is required by AWS for actions/checkout

jobs:
  prod-deploy:
    uses: stacs/actions/.github/workflows/aws-deploy-prod.yaml@v1
    secrets: inherit
    with:
      aws_region: us-east-1
      ecr_repository_name: posted-feedback
      ecs_task_definition_name: posted-feedback
      ecs_container_name: posted-feedback-container
      qa_image_name: ${{inputs.qa_image_name}}
      prod_image_name: ${{inputs.prod_image_name}}
